objects/Headlines__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reference_Link__c</fullName>
        <label>Reference Link</label>
        <type>Url</type>
    </fields>
    <label>Headlines</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Headlines Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Headlines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DE_HeadlinesService.cls
public class DE_HeadlinesService {
    
    @AuraEnabled
    public static String getHeadlines(String deLimiter)
    {
        String healdlinesString='';
        List<Headlines__c> headlines=[SELECT Content__c,Reference_Link__c from Headlines__c where Active__c =true ORDER BY Priority__c DESC];
        for(Headlines__c headline:headlines)
        {
            if(headline.Reference_Link__c!=null)
            {
            	healdlinesString=healdlinesString+' '+headline.Content__c+' - <a href="'+headline.Reference_Link__c+'" target="_blank">More Details</a>  '+deLimiter+' ';
            }
            else
            {
                healdlinesString=healdlinesString+' '+headline.Content__c+' '+deLimiter+' ';

            }
        }
        return healdlinesString;
    }
    @AuraEnabled
    public static String getVerticalHeadlines(String deLimiter)
    {
        String healdlinesString='';
        List<Headlines__c> headlines=[SELECT Content__c,Reference_Link__c  from Headlines__c where Active__c =true ORDER BY Priority__c DESC];
        for(Headlines__c headline:headlines)
        {
             if(headline.Reference_Link__c!=null)
            {
            	healdlinesString=healdlinesString+' '+headline.Content__c+' - <a href="'+headline.Reference_Link__c+'" target="_blank">More Details</a><br>  '+deLimiter+'<br> ';
            }
            else
            {
                healdlinesString=healdlinesString+' '+headline.Content__c+' <br>'+deLimiter+'<br> ';

            }
        }
        return healdlinesString;
    }

}